### ISSUE TITLE
Cache issue with Gemfire

### ISSUE THREAD

**Issue by ranadeep-sharma** [ranadeep-sharma/tutorial-repo#5]
Cache issue with Gemfire. PFA logs   @ranadeep-sh 
Can you please take a look?

The following is a high level task list.
- [x] Recreate issue in DEV environment.
- [x] Debug in DEV environment.
- [x] Fix code in DEV environment. Unit testing as well.
- [ ] Deploy and test in UNIT environment.
- [x] Once QA verified, merge code to GitHub repo and initiate release process.

**Comment by ranadeep-sh** [comment]
It's completed. Hence closing it.
Regards,
Ranadeep-SH

**Comment by ranadeep-sh** [comment]
Please test thoroughly in DEV environment.

**Comment by ranadeep-sharma** [comment]
Done. 
Please check the JUnit test cases commited to our branch. You can close this issue from your end if everything looks good.

**Comment by ranadeep-sh** [comment]
All is good. I am closing it. Thanks.
